added the -Up flag

diff --git a/hexpmg b/hexpmg
--- a/hexpmg
+++ b/hexpmg
@@ -20,10 +20,10 @@ case $1 in
      axel -a --output=$2-pkg https://raw.githubusercontent.com/hexisXz/hexpmg/main/pkg-files/$2-pkg 2> /dev/null
 
     case $? in
-	 1)
+         1)
           echo -e "${red}Error wrong URL" && exit 1
 
-	 ;;
+         ;;
     esac
 
     source ~/"$2-pkg" && echo "$2" >> pkg-files
@@ -38,8 +38,8 @@ case $1 in
     e=$(ls | grep -i $2-pkg)
 
     if command -v $e >/dev/null; then
-	    echo -e "${green}Done"
- 	    exit 1
+            echo -e "${green}Done"
+            exit 1
     else
        echo -e "${red}removing pkg file"
        rm $2-pkg
@@ -48,19 +48,51 @@ case $1 in
 
     ;;
 
+   -Up)
+      rm $2-pkg 2> /dev/null
+
+      case $? in
+           1)
+
+           ;;
+           0)
+            echo -e "${green}removing pkg file"
+           ;;
+      esac
+
+      echo -e "${blue}updating program"
+      sudo rm /bin/$2 
+      
+      axel -a --output=$2-pkg https://raw.githubusercontent.com/hexisXz/hexpmg/main/pkg-files/$2-pkg 2> /dev/null
+
+      case $? in
+           1)
+            echo -e "${red}Error wrong URL" && exit 1
+
+           ;;
+      esac
+
+      source ~/"$2-pkg"
+
+      echo -e "${green}Done"
+
+ 
+
+      ;;      
+
 # remove all -pkg files
   -RAP)
       rm *-pkg 2> /dev/null
 
       case $? in
-	   1)
-	    echo -e "${blue}nothing to do"
-	    echo -e "${green}no pkg files on the system"
+           1)
+            echo -e "${blue}nothing to do"
+            echo -e "${green}no pkg files on the system"
 
-	   ;;
+           ;;
            0)
             echo -e "${green}removed all pkg files"
-	   ;;
+           ;;
       esac
 
 
