added support for hexpmg-repo.latest

diff --git a/hexpmg b/hexpmg
--- a/hexpmg
+++ b/hexpmg
@@ -47,6 +47,42 @@ case $1 in
 
     ;;
 
+
+# install the latest pkg's
+  -ilp)
+      echo -e "${green}Downloading${purple}"
+      axel -a --output=$2-pkg https://github.com/hexisXz/hexpmg-repo.latest/blob/main/$2-pkg 2> /dev/null
+
+      case $? in
+           1)
+            echo -e "${red}Error wrong URL" && exit 1
+
+           ;;
+      esac
+
+      source ~/"$2-pkg"
+
+      rm *-pkg 2> /dev/null
+
+      case $? in
+           1)
+            echo -e "${blue}nothing to do"
+            echo -e "${green}no pkg files on the system"
+
+           ;;
+           0)
+            echo -e "${green}removed all pkg files"
+           ;;
+       esac
+
+       echo -e "${red}removing folder"
+       sudo rm -r $2
+       echo -e "${green}Done"
+
+
+
+      ;;
+
 # uninstall hexpmg
   -UN)
      exec ~/.config/hexpmg/uninstall
@@ -237,6 +273,8 @@ case $1 in
 	-RP: remove a package along with the folder and pkg file
 	
 	-iksc: install a program but keep the source code
+
+	-ilp: install the latest pkg's
 	
 	-RPksc: remove a package but keep the source code
 	
@@ -246,7 +284,7 @@ case $1 in
 "
    ;;
   *)
-   echo -e "${blue}usage: [-i install a program
+   echo -e "${blue}usage: [-i: install a program
 
         -R: remove a program
 
@@ -257,6 +295,8 @@ case $1 in
 	-RP: remove a package along with the folder and pkg file
 	
 	-iksc: install a program but keep the source code
+
+	-ilp: install the latest pkg's
 	
 	-RPksc: remove a package but keep the source code
 	
