update

diff --git a/uninstall/uninstall b/uninstall/uninstall
--- a/uninstall/uninstall
+++ b/uninstall/uninstall
@@ -1,7 +1,7 @@
-#!/bin/bash
+#!/bin/sh
 
 
-sudo rm /bin/hexpmg && sudo rm -r ~/.config/hexpmg
+sudo rm /bin/hexpmg && sudo rm -r ~/.config/hexpmg && echo "uninstalled." || echo "ERROR."
 
 
 
